services:
  calibration-tools:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calibration-tools
    environment:
      PYTHONPATH: /workspace/src
    volumes:
      - .:/workspace
      - ~/hive-calib:/hive-calib