services:
  dev:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ../..:/workspace
      - /dev/v4l:/dev/v4l
    devices:
      - /dev/bus/usb:/dev/bus/usb
    group_add:
      - video
      - plugdev